In [180]:
%pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [181]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [182]:
%pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [183]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [184]:
import pandas as pd

In [185]:
df=pd.read_csv('transactions_large.csv')
print(df.head())

         date               description   amount    type       category
0  2025-08-17  Mis@@@cellaneous expense  1649.83   debit         Others
1  2025-07-08      50 in Amusement park      NaN   debit  Entertainment
2  2025-08-18         Pharmacy purchase  2134.13  credit         Health
3  2025-09-06           Myntra shopping  2464.09  credit       Shopping
4  2025-07-26           Spotify premium  2363.98  credit  Entertainment


In [186]:
print(df.describe())

            amount
count  1499.000000
mean   4911.656484
std    2836.861034
min      51.850000
25%    2494.855000
50%    4820.550000
75%    7340.235000
max    9999.150000


In [187]:
print(df.isna().any())

date           False
description    False
amount          True
type           False
category       False
dtype: bool


In [188]:
print(df.isna().any().any())

True


In [189]:
df.loc[1,"amount"]=pd.NA
df

,date,description,amount,type,category
0,2025-08-17,Mis@@@cellaneous expense,1649.83,debit,Others
1,2025-07-08,50 in Amusement park,NaN,debit,Entertainment
2,2025-08-18,Pharmacy purchase,2134.13,credit,Health
3,2025-09-06,Myntra shopping,2464.09,credit,Shopping
4,2025-07-26,Spotify premium,2363.98,credit,Entertainment
...,...,...,...,...,...
1495,2025-09-13,Internet recharge,6062.59,debit,Bills
1496,2025-10-25,Train ticket,779.28,credit,Travel
1497,2025-10-19,Miscellaneous expense,7288.46,debit,Others
1498,2025-06-15,Protein supplements,102.72,debit,Health


In [190]:
df.to_csv('transactions_large.csv',index=False)

In [191]:
df.fillna(0,inplace=True)
df

,date,description,amount,type,category
0,2025-08-17,Mis@@@cellaneous expense,1649.83,debit,Others
1,2025-07-08,50 in Amusement park,0.00,debit,Entertainment
2,2025-08-18,Pharmacy purchase,2134.13,credit,Health
3,2025-09-06,Myntra shopping,2464.09,credit,Shopping
4,2025-07-26,Spotify premium,2363.98,credit,Entertainment
...,...,...,...,...,...
1495,2025-09-13,Internet recharge,6062.59,debit,Bills
1496,2025-10-25,Train ticket,779.28,credit,Travel
1497,2025-10-19,Miscellaneous expense,7288.46,debit,Others
1498,2025-06-15,Protein supplements,102.72,debit,Health


In [192]:
df=df.applymap(lambda x : x.lower() if isinstance(x,str) else x)
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7140\382033471.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df=df.applymap(lambda x : x.lower() if isinstance(x,str) else x)


,date,description,amount,type,category
0,2025-08-17,mis@@@cellaneous expense,1649.83,debit,others
1,2025-07-08,50 in amusement park,0.00,debit,entertainment
2,2025-08-18,pharmacy purchase,2134.13,credit,health
3,2025-09-06,myntra shopping,2464.09,credit,shopping
4,2025-07-26,spotify premium,2363.98,credit,entertainment
...,...,...,...,...,...
1495,2025-09-13,internet recharge,6062.59,debit,bills
1496,2025-10-25,train ticket,779.28,credit,travel
1497,2025-10-19,miscellaneous expense,7288.46,debit,others
1498,2025-06-15,protein supplements,102.72,debit,health


pip install nltk

In [193]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [194]:
def clean_text(text):
    if isinstance(text,str):
        text=re.sub(r'\d+','',text)
        text=re.sub(r'[^\w\s]','',text)
        words=text.split()
        sw=set(stopwords.words('english'))
        words=[word for word in words if word not in sw]
        return ' '.join(words)
    else:
        return text

In [195]:
df['description']=df['description'].apply(clean_text)
df

,date,description,amount,type,category
0,2025-08-17,miscellaneous expense,1649.83,debit,others
1,2025-07-08,amusement park,0.00,debit,entertainment
2,2025-08-18,pharmacy purchase,2134.13,credit,health
3,2025-09-06,myntra shopping,2464.09,credit,shopping
4,2025-07-26,spotify premium,2363.98,credit,entertainment
...,...,...,...,...,...
1495,2025-09-13,internet recharge,6062.59,debit,bills
1496,2025-10-25,train ticket,779.28,credit,travel
1497,2025-10-19,miscellaneous expense,7288.46,debit,others
1498,2025-06-15,protein supplements,102.72,debit,health


In [196]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [197]:
df['type']=le.fit_transform(df['type'])
df

,date,description,amount,type,category
0,2025-08-17,miscellaneous expense,1649.83,1,others
1,2025-07-08,amusement park,0.00,1,entertainment
2,2025-08-18,pharmacy purchase,2134.13,0,health
3,2025-09-06,myntra shopping,2464.09,0,shopping
4,2025-07-26,spotify premium,2363.98,0,entertainment
...,...,...,...,...,...
1495,2025-09-13,internet recharge,6062.59,1,bills
1496,2025-10-25,train ticket,779.28,0,travel
1497,2025-10-19,miscellaneous expense,7288.46,1,others
1498,2025-06-15,protein supplements,102.72,1,health


In [198]:
le_cat = LabelEncoder()
y = le_cat.fit_transform(df['category'])


In [199]:
print(df.columns)

Index(['date', 'description', 'amount', 'type', 'category'], dtype='object')


In [200]:
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack
tfidf=TfidfVectorizer(max_features=1000)
X_text= tfidf.fit_transform(df['description'])

X_num=df[['amount','type']].values

X_final = hstack([X_text, X_num])


y = df['category']
y


0              others
1       entertainment
2              health
3            shopping
4       entertainment
            ...      
1495            bills
1496           travel
1497           others
1498           health
1499           health
Name: category, Length: 1500, dtype: object

In [201]:
df.to_csv('transactions_cleaned.csv', index=False)

In [202]:
X=df.drop('category',axis=1)
Y=df['category']

In [203]:
X = df.drop(columns=["category", "date"])   # remove unwanted text column
y = df["category"]

In [204]:
df['type'].unique()

array([1, 0])

In [205]:
le_cat = LabelEncoder()
y = le_cat.fit_transform(df['category']) 

In [206]:
from sklearn.model_selection import train_test_split
import numpy as np
# Ensure target variable is a 1-D numpy array named `y` to avoid shape mismatches
y = df['category'].values if 'y' not in globals() else np.asarray(y).ravel()
# Split the features and target consistently (use X_final which is the combined text+numeric features)
X_train, X_test, Y_train, Y_test = train_test_split(X_final, y, test_size=0.2, random_state=42)
print('X_train shape:', getattr(X_train, 'shape', None))
print('Y_train shape:', getattr(Y_train, 'shape', None))

X_train shape: (1200, 64)
Y_train shape: (1200,)


In [207]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

model = LogisticRegression(max_iter=5000, solver='lbfgs')
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

print("Accuracy :",accuracy_score(Y_test,Y_pred))

Accuracy : 1.0


In [208]:
print(classification_report(Y_test, Y_pred))
print(confusion_matrix(Y_test, Y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        54
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        46
           4       1.00      1.00      1.00        47
           5       1.00      1.00      1.00        37
           6       1.00      1.00      1.00        39

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[36  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0]
 [ 0  0 41  0  0  0  0]
 [ 0  0  0 46  0  0  0]
 [ 0  0  0  0 47  0  0]
 [ 0  0  0  0  0 37  0]
 [ 0  0  0  0  0  0 39]]


In [209]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=200,random_state=42)
rf.fit(X_train,Y_train)

,n_estimators,200
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [210]:
pred_rf = rf.predict(X_test)

print("RF Accuracy:", accuracy_score(Y_test, pred_rf))
print(classification_report(Y_test, pred_rf))
print(confusion_matrix(Y_test, pred_rf))

RF Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        54
           2       1.00      1.00      1.00        41
           3       1.00      1.00      1.00        46
           4       1.00      1.00      1.00        47
           5       1.00      1.00      1.00        37
           6       1.00      1.00      1.00        39

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[36  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0]
 [ 0  0 41  0  0  0  0]
 [ 0  0  0 46  0  0  0]
 [ 0  0  0  0 47  0  0]
 [ 0  0  0  0  0 37  0]
 [ 0  0  0  0  0  0 39]]


In [211]:
from xgboost import XGBClassifier
from scipy import sparse

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.1,
    eval_metric='mlogloss'
)

# Train on the combined feature matrix (X_train comes from X_final)
xgb.fit(X_train, Y_train)

# Predict on the test set. Use X_test (same feature columns as X_train).
# If X_test is sparse and XGB has issues, convert to dense for small datasets:
X_pred_input = X_test
if sparse.issparse(X_pred_input):
    try:
        # keep sparse if supported; otherwise convert to dense (careful with large data)
        X_pred_input = X_pred_input.tocsr()
    except Exception:
        X_pred_input = X_pred_input.toarray()

pred_xgb = xgb.predict(X_pred_input)

print("Accuracy :", accuracy_score(Y_test, pred_xgb))

Accuracy : 1.0


In [212]:
import joblib

joblib.dump(model, "best_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")


NameError: name 'vectorizer' is not defined